name: Build and push Docker image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    env:
      Image_Name: my-app
    steps:
      - uses: actions/checkout@v3
      - name: Build and push the image
        run: |
          docker login --username ${{ secrets.GH_USERNAME}} --password ${{ secrets.GH_PAT}} ghcr.io
          docker build . --tag ghcr.io/${{ secrets.GH_USERNAME}}/${{ env.Image_Name}}:${{ github.sha}}
          docker push ghcr.io/${{ secrets.GH_USERNAME}}/${{ env.Image_Name}}:${{ github.sha}}

  test:
    runs-on: ubuntu-latest
    env:
      Image_Name: my-app
    needs: build_and_push
    steps: 
      - name: Pull and run tests
        run: |
          docker login --username ${{ secrets.GH_USERNAME}} --password ${{ secrets.GH_PAT}} ghcr.io
          docker pull ghcr.io/${{ secrets.GH_USERNAME}}/${{ env.Image_Name}}:${{ github.sha}}
          docker run --rm ghcr.io/${{ secrets.GH_USERNAME}}/${{ env.Image_Name}}:${{ github.sha}} pytest